### ISSUE TITLE
【Want】秘伝のタレの継ぎ足しを自動化してほしい

### ISSUE THREAD

**Issue by karinto3375** [dayaman/HidenNoTare#6]
# 概要
秘伝のタレの継ぎ足しを自動化してほしい
# 目的
毎朝早起きして継ぎ足すのがキツいため
# 提案内容
現状の手法ではユーザーが毎朝早起きをして秘伝のタレを作り、継ぎ足していくしか味に時代の深みを加えることができないがこれらを自動化することによって放っておけば自然に秘伝のタレ(令和最新版)ができるのではないだろうか？

**Comment by pekko1215** [comment]
GithubActionsに、scheduleという機能があります。  
定期実行可能なので、つぎ足す工程をタスク化すればたぶん行けるかと。  

https://gotohayato.com/content/514/

**Comment by dayaman** [comment]
レシピが秘伝なだけで継ぎ足しをするタイプのタレではないです。
同じレシピで作成することで品質は保てるので、タレが切れてから新しく作る方法で何も問題はありません。
