### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by udaken** [dayaman/HidenNoTare#7]
`LISENCE.txt`
> This recipe is lisenced by Barbecue Source Distribution.

`s`と`c`が逆に思うのですが(正しくは`LICENSE.txt`)、意図されれているのでしょうか？

**Comment by dayaman** [comment]
Typoです！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by dayaman** [comment]
typoというか間違って覚えてました

**Comment by udaken** [comment]
そういうこと、ありますよね。
